FROM scratch
LABEL org.entando.bundle-name="scw"
ADD .entando/output/descriptors/ .
ADD microfrontends/et-widget/build widgets/et-widget
ADD microfrontends/et-widget-config/build widgets/et-widget-config
